FROM openjdk:8-jdk-alpine
VOLUME /tmp
EXPOSE 2505
COPY /target/architecture-discovery-service-0.0.1-SNAPSHOT.jar architecture-discovery-service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["/usr/bin/java"]
CMD ["-jar","architecture-discovery-service-0.0.1-SNAPSHOT.jar"]
